sed -i 's/ENSCDR/Camelus_dromedarius/g' *.fa
sed -i 's/MGP_CBAJ/Mus_musculus/g' *.fa
sed -i 's/ENSMPU/Mustela_putorius_furo/g' *.fa
sed -i 's/ENSARW/Apteryx_rowi/g' *.fa
sed -i 's/ENSCCN/Castor_canadensis/g' *.fa
sed -i 's/ENSXET/Xenopus_tropicalis/g' *.fa
sed -i 's/ENSTGU/Taeniopygia_guttata/g' *.fa
sed -i 's/ENSSHB/Strigops_habroptila/g' *.fa
sed -i 's/ENSCPV/Camarhynchus_parvulus/g' *.fa
sed -i 's/ENSANA/Aotus_nancymaae/g' *.fa
sed -i 's/ENSORL/Oryzias_latipes/g' *.fa
sed -i 's/ENSBJA/Buteo_japonicus/g' *.fa
sed -i 's/ENSACL/Astatotilapia_calliptera/g' *.fa
sed -i 's/ENSVUR/Vombatus_ursinus/g' *.fa
sed -i 's/ENSMIC/Microcebus_murinus/g' *.fa
sed -i 's/ENSSCU/Struthio_camelus_australis/g' *.fa
sed -i 's/ENSOTS/Oncorhynchus_tshawytscha/g' *.fa
sed -i 's/ENSCHY/Cervus_hanglu_yarkandensis/g' *.fa
sed -i 's/ENSSGR/Sinocyclocheilus_grahami/g' *.fa
sed -i 's/ENSOSI/Oryzias_sinensis/g' *.fa
sed -i 's/ENSCCR/Cyprinus_carpio_carpio/g' *.fa
sed -i 's/ENSPTI/Panthera_tigris_altaica/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSAPL/Anas_platyrhynchos_platyrhynchos/g' *.fa
sed -i 's/ENSHGLM/Heterocephalus_glaber/g' *.fa
sed -i 's/ENSECA/Equus_caballus/g' *.fa
sed -i 's/ENSNSU/Notechis_scutatus/g' *.fa
sed -i 's/ENSPPR/Panthera_pardus/g' *.fa
sed -i 's/ENSMMN/Monodon_monoceros/g' *.fa
sed -i 's/ENSCAT/Cercocebus_atys/g' *.fa
sed -i 's/ENSAMX/Astyanax_mexicanus/g' *.fa
sed -i 's/ENSPVI/Pogona_vitticeps/g' *.fa
sed -i 's/ENSCAR/Carassius_auratus/g' *.fa
sed -i 's/ENSMAL/Monopterus_albus/g' *.fa
sed -i 's/ENSPSM/Prolemur_simus/g' *.fa
sed -i 's/ENSCCE/Cyanistes_caeruleus/g' *.fa
sed -i 's/ENSPCO/Propithecus_coquereli/g' *.fa
sed -i 's/ENSELU/Esox_lucius/g' *.fa
sed -i 's/ENSCLA/Chinchilla_lanigera/g' *.fa
sed -i 's/ENSTGE/Theropithecus_gelada/g' *.fa
sed -i 's/ENSRNO/Rattus_norvegicus/g' *.fa
sed -i 's/ENSPLA/Poecilia_latipinna/g' *.fa
sed -i 's/ENSPRE/Poecilia_reticulata/g' *.fa
sed -i 's/ENSCGO/Cottoperca_gobio/g' *.fa
sed -i 's/ENSPTE/Piliocolobus_tephrosceles/g' *.fa
sed -i 's/ENSMFA/Macaca_fascicularis/g' *.fa
sed -i 's/ENSCCA/Cebus_capucinus_imitator/g' *.fa
sed -i 's/ENSDLA/Dicentrarchus_labrax/g' *.fa
sed -i 's/ENSMSI/Mus_spicilegus/g' *.fa
sed -i 's/ENSMEU/Notamacropus_eugenii/g' *.fa
sed -i 's/ENSHBU/Haplochromis_burtoni/g' *.fa
sed -i 's/ENSMZE/Maylandia_zebra/g' *.fa
sed -i 's/ENSTTR/Tursiops_truncatus/g' *.fa
sed -i 's/ENSSPA/Stegastes_partitus/g' *.fa
sed -i 's/ENSCGR/Cricetulus_griseus/g' *.fa
sed -i 's/ENSRFE/Rhinolophus_ferrumequinum/g' *.fa
sed -i 's/ENSOKI/Oncorhynchus_kisutch/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSMMU/Macaca_mulatta/g' *.fa
sed -i 's/ENSMUN/Melopsittacus_undulatus/g' *.fa
sed -i 's/ENSEAS/Equus_asinus_asinus/g' *.fa
sed -i 's/ENSPAN/Papio_anubis/g' *.fa
sed -i 's/ENSACU/Athene_cunicularia/g' *.fa
sed -i 's/ENSSMA/Scophthalmus_maximus/g' *.fa
sed -i 's/ENSZCA/Zalophus_californianus/g' *.fa
sed -i 's/MGP_BALBcJ/Mus_musculus/g' *.fa
sed -i 's/ENSCCR/Cyprinus_carpio/g' *.fa
sed -i 's/ENSSLU/Sander_lucioperca/g' *.fa
sed -i 's/ENSXMA/Xiphophorus_maculatus/g' *.fa
sed -i 's/MGP_LPJ/Mus_musculus/g' *.fa
sed -i 's/ENSENL/Echeneis_naucrates/g' *.fa
sed -i 's/ENSPSI/Pelodiscus_sinensis/g' *.fa
sed -i 's/ENSCGR/Cricetulus_griseus/g' *.fa
sed -i 's/ENSCAP/Cavia_aperea/g' *.fa
sed -i 's/ENSNBR/Neolamprologus_brichardi/g' *.fa
sed -i 's/ENSCCR/Cyprinus_carpio/g' *.fa
sed -i 's/ENSUMA/Ursus_maritimus/g' *.fa
sed -i 's/ENSCPI/Chrysolophus_pictus/g' *.fa
sed -i 's/ENSCMM/Cairina_moschata_domestica/g' *.fa
sed -i 's/ENSVPA/Vicugna_pacos/g' *.fa
sed -i 's/ENSBOB/Bubo_bubo/g' *.fa
sed -i 's/ENSMUG/Meriones_unguiculatus/g' *.fa
sed -i 's/ENSOME/Oryzias_melastigma/g' *.fa
sed -i 's/ENSZLM/Zosterops_lateralis_melanops/g' *.fa
sed -i 's/ENSSFA/Salarias_fasciatus/g' *.fa
sed -i 's/ENSUAM/Ursus_americanus/g' *.fa
sed -i 's/ENSAHA/Apteryx_haastii/g' *.fa
sed -i 's/ENSGEV/Gopherus_evgoodei/g' *.fa
sed -i 's/ENSPST/Pavo_cristatus/g' *.fa
sed -i 's/ENSCJP/Coturnix_japonica/g' *.fa
sed -i 's/ENSFTI/Falco_tinnunculus/g' *.fa
sed -i 's/ENSOAR/Ovis_aries/g' *.fa
sed -i 's/ENSCHA/Clupea_harengus/g' *.fa
sed -i 's/ENSNNA/Naja_naja/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSLCR/Larimichthys_crocea/g' *.fa
sed -i 's/ENSLLE/Leptobrachium_leishanense/g' *.fa
sed -i 's/ENSPSN/Phocoena_sinus/g' *.fa
sed -i 's/ENSFDA/Fukomys_damarensis/g' *.fa
sed -i 's/MGP_129S1SvImJ/Mus_musculus/g' *.fa
sed -i 's/ENSOCU/Oryctolagus_cuniculus/g' *.fa
sed -i 's/ENSOGA/Otolemur_garnettii/g' *.fa
sed -i 's/ENSGAC/Gasterosteus_aculeatus/g' *.fa
sed -i 's/ENSSSA/Salmo_salar/g' *.fa
sed -i 's/ENSXCO/Xiphophorus_couchianus/g' *.fa
sed -i 's/ENSIPU/Ictalurus_punctatus/g' *.fa
sed -i 's/ENSPRN/Parambassis_ranga/g' *.fa
sed -i 's/ENSRBI/Rhinopithecus_bieti/g' *.fa
sed -i 's/ENSVKK/Varanus_komodoensis/g' *.fa
sed -i 's/ENSTRU/Takifugu_rubripes/g' *.fa
sed -i 's/ENSPPY/Pongo_abelii/g' *.fa
sed -i 's/ENSHGLF/Heterocephalus_glaber/g' *.fa
sed -i 's/MGP_C57BL6NJ/Mus_musculus/g' *.fa
sed -i 's/ENSMCS/Malurus_cyaneus_samueli/g' *.fa
sed -i 's/ENSCWA/Catagonus_wagneri/g' *.fa
sed -i 's/ENSJHY/Junco_hyemalis/g' *.fa
sed -i 's/ENSBMS/Balaenoptera_musculus/g' *.fa
sed -i 's/ENSCPI/Chrysemys_picta_bellii/g' *.fa
sed -i 's/ENSSBO/Saimiri_boliviensis_boliviensis/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSAPO/Acanthochromis_polyacanthus/g' *.fa
sed -i 's/ENSAZO/Anas_zonorhyncha/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSOAR/Ovis_aries/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSGAF/Gambusia_affinis/g' *.fa
sed -i 's/ENSPME/Poecilia_mexicana/g' *.fa
sed -i 's/ENSPTX/Pseudonaja_textilis/g' *.fa
sed -i 's/ENSPMA/Petromyzon_marinus/g' *.fa
sed -i 's/ENSCPG/Calidris_pygmaea/g' *.fa
sed -i 's/ENSAMX/Astyanax_mexicanus/g' *.fa
sed -i 's/ENSMAM/Mastacembelus_armatus/g' *.fa
sed -i 's/ENSDNV/Dromaius_novaehollandiae/g' *.fa
sed -i 's/ENSMMD/Myripristis_murdjan/g' *.fa
sed -i 's/ENSCHI/Capra_hircus/g' *.fa
sed -i 's/ENSNML/Neogobius_melanostomus/g' *.fa
sed -i 's/ENSPNA/Pygocentrus_nattereri/g' *.fa
sed -i 's/ENSHCO/Hippocampus_comes/g' *.fa
sed -i 's/ENSSMR/Salvator_merianae/g' *.fa
sed -i 's/ENSSAN/Sinocyclocheilus_anshuiensis/g' *.fa
sed -i 's/ENSOMY/Oncorhynchus_mykiss/g' *.fa
sed -i 's/ENSCJA/Callithrix_jacchus/g' *.fa
sed -i 's/MGP_FVBNJ/Mus_musculus/g' *.fa
sed -i 's/ENSDNO/Dasypus_novemcinctus/g' *.fa
sed -i 's/ENSMNE/Macaca_nemestrina/g' *.fa
sed -i 's/ENSOAN/Ornithorhynchus_anatinus/g' *.fa
sed -i 's/ENSLCN/Lynx_canadensis/g' *.fa
sed -i 's/ENSACI/Amphilophus_citrinellus/g' *.fa
sed -i 's/MGP_NZOHlLtJ/Mus_musculus/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSFAL/Ficedula_albicollis/g' *.fa
sed -i 's/ENSCSR/Chelydra_serpentina/g' *.fa
sed -i 's/ENSCMI/Callorhinchus_milii/g' *.fa
sed -i 's/ENSUPA/Urocitellus_parryii/g' *.fa
sed -i 's/ENSTMT/Terrapene_carolina_triunguis/g' *.fa
sed -i 's/ENSOAB/Oreochromis_aureus/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSCCR/Cyprinus_carpio/g' *.fa
sed -i 's/ENSLCA/Lates_calcarifer/g' *.fa
sed -i 's/ENSECR/Erpetoichthys_calabaricus/g' *.fa
sed -i 's/ENSEEE/Electrophorus_electricus/g' *.fa
sed -i 's/ENSVVU/Vulpes_vulpes/g' *.fa
sed -i 's/MGP_AKRJ/Mus_musculus/g' *.fa
sed -i 's/ENSSCA/Serinus_canaria/g' *.fa
sed -i 's/ENSCPR/Crocodylus_porosus/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSCUS/Catharus_ustulatus/g' *.fa
sed -i 's/MGP_AJ/Mus_musculus/g' *.fa
sed -i 's/ENSSTU/Salmo_trutta/g' *.fa
sed -i 's/ENSDOR/Dipodomys_ordii/g' *.fa
sed -i 's/ENSMGA/Meleagris_gallopavo/g' *.fa
sed -i 's/ENSKMA/Kryptolebias_marmoratus/g' *.fa
sed -i 's/ENSCIN/Ciona_intestinalis/g' *.fa
sed -i 's/ENSPEM/Peromyscus_maniculatus_bairdii/g' *.fa
sed -i 's/ENSMLU/Myotis_lucifugus/g' *.fa
sed -i 's/ENSBIX/Bos_indicus_x_Bos_taurus/g' *.fa
sed -i 's/MGP_C3HHeJ/Mus_musculus/g' *.fa
sed -i 's/ENSGAL/Gallus_gallus/g' *.fa
sed -i 's/ENSACO/Amazona_collaria/g' *.fa
sed -i 's/ENSPCI/Phascolarctos_cinereus/g' *.fa
sed -i 's/ENSCSAV/Ciona_savignyi/g' *.fa
sed -i 's/ENSMMO/Mola_mola/g' *.fa
sed -i 's/ENSFHE/Fundulus_heteroclitus/g' *.fa
sed -i 's/ENSABR/Anser_brachyrhynchus/g' *.fa
sed -i 's/MGP_NODShiLtJ/Mus_musculus/g' *.fa
sed -i 's/ENSTBE/Tupaia_belangeri/g' *.fa
sed -i 's/ENSSOC/Strix_occidentalis_caurina/g' *.fa
sed -i 's/ENSSRH/Sinocyclocheilus_rhinocerous/g' *.fa
sed -i 's/ENSAPL/Anas_platyrhynchos/g' *.fa
sed -i 's/ENSLLT/Laticauda_laticaudata/g' *.fa
sed -i 's/ENSSTO/Ictidomys_tridecemlineatus/g' *.fa
sed -i 's/ENSPCE/Pelusios_castaneus/g' *.fa
sed -i 's/ENSCHO/Choloepus_hoffmanni/g' *.fa
sed -i 's/ENSEBU/Eptatretus_burgeri/g' *.fa
sed -i 's/ENSRRO/Rhinopithecus_roxellana/g' *.fa
sed -i 's/ENSNME/Numida_meleagris/g' *.fa
sed -i 's/ENSSOR/Sphaeramia_orbicularis/g' *.fa
sed -i 's/ENSCAF/Canis_lupus_dingo/g' *.fa
sed -i 's/ENSMMS/Moschus_moschiferus/g' *.fa
sed -i 's/ENSLBE/Labrus_bergylta/g' *.fa
sed -i 's/ENSONI/Oreochromis_niloticus/g' *.fa
sed -i 's/ENSLOC/Lepisosteus_oculatus/g' *.fa
sed -i 's/ENSMMM/Marmota_marmota_marmota/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSORL/Oryzias_latipes/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSSAU/Sparus_aurata/g' *.fa
sed -i 's/ENSPKI/Paramormyrops_kingsleyae/g' *.fa
sed -i 's/ENSCSE/Cynoglossus_semilaevis/g' *.fa
sed -i 's/ENSCVA/Cyprinodon_variegatus/g' *.fa
sed -i 's/ENSSHA/Sarcophilus_harrisii/g' *.fa
sed -i 's/ENSNVI/Neovison_vison/g' *.fa
sed -i 's/ENSODE/Octodon_degus/g' *.fa
sed -i 's/ENSCAB/Chelonoidis_abingdonii/g' *.fa
sed -i 's/ENSNPE/Nothoprocta_perdicaria/g' *.fa
sed -i 's/ENSNGA/Nannospalax_galili/g' *.fa
sed -i 's/ENSCRF/Cyanoderma_ruficeps/g' *.fa
sed -i 's/ENSBSL/Betta_splendens/g' *.fa
sed -i 's/ENSCLM/Cyclopterus_lumpus/g' *.fa
sed -i 's/ENSBGR/Bos_grunniens/g' *.fa
sed -i 's/ENSCPU/Calidris_pugnax/g' *.fa
sed -i 's/MGP_SPRETEiJ/Mus_spretus/g' *.fa
sed -i 's/ENSSSU/Suricata_suricatta/g' *.fa
sed -i 's/MGP_DBA2J/Mus_musculus/g' *.fa
sed -i 's/ENSMLE/Mandrillus_leucophaeus/g' *.fa
sed -i 's/ENSPPA/Pan_paniscus/g' *.fa
sed -i 's/ENSGGO/Gorilla_gorilla_gorilla/g' *.fa
sed -i 's/ENSAOC/Amphiprion_ocellaris/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/MGP_PWKPhJ/Mus_musculus_musculus/g' *.fa
sed -i 's/ENSOSU/Otus_sunia/g' *.fa
sed -i 's/ENSPFO/Poecilia_formosa/g' *.fa
sed -i 's/ENSMUS/Mus_musculus/g' *.fa
sed -i 's/ENSEEU/Erinaceus_europaeus/g' *.fa
sed -i 's/ENSATE/Anabas_testudineus/g' *.fa
sed -i 's/ENSETE/Echinops_telfairi/g' *.fa
sed -i 's/MGP_CASTEiJ/Mus_musculus_castaneus/g' *.fa
sed -i 's/ENSBTA/Bos_taurus/g' *.fa
sed -i 's/MGP_WSBEiJ/Mus_musculus_domesticus/g' *.fa
sed -i 's/ENSLAC/Latimeria_chalumnae/g' *.fa
sed -i 's/ENSPNY/Pundamilia_nyererei/g' *.fa
sed -i 's/ENSPTR/Pan_troglodytes/g' *.fa
sed -i 's/MGP_PahariEiJ/Mus_pahari/g' *.fa
sed -i 's/ENSCAF/Canis_lupus_familiaris/g' *.fa
sed -i 's/ENSSPU/Sphenodon_punctatus/g' *.fa
sed -i 's/ENSCHA/Scleropages_formosus/g' *.fa
sed -i 's/ENSTSY/Carlito_syrichta/g' *.fa
sed -i 's/ENSACC/Aquila_chrysaetos_chrysaetos/g' *.fa
sed -i 's/ENSCAN/Colobus_angolensis_palliatus/g' *.fa
sed -i 's/ENSSAR/Sorex_araneus/g' *.fa
sed -i 's/ENSOJA/Oryzias_javanicus/g' *.fa
sed -i 's/ENSCMU/Corvus_moneduloides/g' *.fa
sed -i 's/ENSPCL/Phasianus_colchicus/g' *.fa
sed -i 's/ENSBIX/Bos_indicus_x_Bos_taurus/g' *.fa
sed -i 's/ENSPCT/Physeter_catodon/g' *.fa
sed -i 's/ENSMAU/Mesocricetus_auratus/g' *.fa
sed -i 's/ENSPMG/Periophthalmus_magnuspinnatus/g' *.fa
sed -i 's/ENSACA/Anolis_carolinensis/g' *.fa
sed -i 's/ENSDLE/Delphinapterus_leucas/g' *.fa
sed -i 's/ENSPMR/Podarcis_muralis/g' *.fa
sed -i 's/ENSMOD/Monodelphis_domestica/g' *.fa
sed -i 's/ENSPVA/Pteropus_vampyrus/g' *.fa
sed -i 's/ENSLAF/Loxodonta_africana/g' *.fa
sed -i 's/ENSOPR/Ochotona_princeps/g' *.fa
sed -i 's/ENSPLO/Panthera_leo/g' *.fa
sed -i 's/ENSCPO/Cavia_porcellus/g' *.fa
sed -i 's/ENSSLD/Seriola_lalandi_dorsalis/g' *.fa
sed -i 's/ENSANI/Accipiter_nisus/g' *.fa
sed -i 's/ENSCAF/Canis_lupus_familiaris/g' *.fa
sed -i 's/ENSCAF/Canis_lupus_familiaris/g' *.fa
sed -i 's/ENSBMU/Bos_mutus/g' *.fa
sed -i 's/ENSMVI/Manacus_vitellinus/g' *.fa
sed -i 's/ENSMOC/Microtus_ochrogaster/g' *.fa
sed -i 's/ENSUTT/Ursus_thibetanus_thibetanus/g' *.fa
sed -i 's/ENSAPE/Amphiprion_percula/g' *.fa
sed -i 's/ENSZAL/Zonotrichia_albicollis/g' *.fa
sed -i 's/ENSFCA/Felis_catus/g' *.fa
sed -i 's/ENSPMJ/Parus_major/g' *.fa
sed -i 's/ENSHHU/Hucho_hucho/g' *.fa
sed -i 's/MGP_CAROLIEiJ/Mus_caroli/g' *.fa
sed -i 's/ENSEGO/Erythrura_gouldiae/g' *.fa
sed -i 's/ENSCGR/Cricetulus_griseus/g' *.fa
sed -i 's/ENSGAG/Gopherus_agassizii/g' *.fa
sed -i 's/ENSGWI/Gouania_willdenowi/g' *.fa
sed -i 's/ENSCHI/Capra_hircus/g' *.fa
sed -i 's/ENSBBB/Bison_bison_bison/g' *.fa
sed -i 's/ENSSDA/Spermophilus_dauricus/g' *.fa
sed -i 's/ENSACD/Anser_cygnoides/g' *.fa
sed -i 's/ENSLSD/Lonchura_striata_domestica/g' *.fa
sed -i 's/ENSSVL/Sciurus_vulgaris/g' *.fa
sed -i 's/ENSLCO/Lepidothrix_coronata/g' *.fa
sed -i 's/ENSDCD/Denticeps_clupeoides/g' *.fa
sed -i 's/ENSPCA/Procavia_capensis/g' *.fa
sed -i 's/ENSGFO/Geospiza_fortis/g' *.fa
sed -i 's/ENSAME/Ailuropoda_melanoleuca/g' *.fa
sed -i 's/ENSCAF/Canis_lupus_familiaris/g' *.fa
sed -i 's/ENSORL/Oryzias_latipes/g' *.fa
sed -i 's/ENSNFU/Nothobranchius_furzeri/g' *.fa
sed -i 's/ENSAOW/Apteryx_owenii/g' *.fa
sed -i 's/ENSSSC/Sus_scrofa/g' *.fa
sed -i 's/ENSSDU/Seriola_dumerili/g' *.fa
sed -i 's/ENSTNI/Tetraodon_nigroviridis/g' *.fa
sed -i 's/ENSDAR/Danio_rerio/g' *.fa
sed -i 's/ENSCSA/Chlorocebus_sabaeus/g' *.fa
sed -i 's/ENSGMO/Gadus_morhua/g' *.fa
sed -i 's/ENSNLE/Nomascus_leucogenys/g' *.fa
sed -i 's/ENSJJA/Jaculus_jaculus/g' *.fa
